# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200, verbose_name='Категория: ')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_text', models.TextField(max_length=5000, verbose_name='')),
                ('com_pubdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('content', models.TextField(verbose_name='Текст поста')),
                ('post_likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('post_cat', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='q.Category', verbose_name='Категория поста')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='com_posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q.Post', verbose_name='Пост'),
        ),
    ]
