# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-datetime']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='datetime',
        ),
    ]
