# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0002_auto_20170211_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-datetime'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='com_pubdate',
            new_name='pubdate',
        ),
    ]
