# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0003_auto_20170211_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое описание статьи(необязательно к заполнению)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=22, verbose_name='Заголовок поста'),
        ),
    ]
