# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0011_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
