# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0012_auto_20170211_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Добавить файл'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Добавить файл'),
        ),
    ]
