# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0014_auto_20170211_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='AltText',
            field=models.CharField(default='', max_length=200, verbose_name='Описание изобрежния'),
        ),
    ]
