# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0015_post_alttext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='upload',
            new_name='ComImage',
        ),
    ]
