# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0016_auto_20170211_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hictory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField(unique=True)),
            ],
        ),
    ]
