# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0017_hictory_regulations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hictory',
            new_name='History',
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-pubdate'], 'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterModelOptions(
            name='regulations',
            options={'ordering': ['-pubdate'], 'verbose_name': 'Правила', 'verbose_name_plural': 'Правила'},
        ),
    ]
